### ISSUE TITLE
HVT & Heatmap View | A line goes up instead of going down for one of the cells | Improper drichlet formation

### ISSUE THREAD

**Issue by SangeetM** [Mu-Sigma/muHVT#6]

**Comment by shubhra2503** [comment]
![Incorrect ](https://user-images.githubusercontent.com/53158022/72154728-65600c00-33d7-11ea-9617-f7626b31456c.png)

Tesselation lines are not getting joined with respective polygon vertices. Hence stray tessellation lines appear. The issue is caused while calculating the exact intersection point and then checking these points for point on polygon. Adding a offset tolerance zone of 0.00001 solved the issue

**Comment by shubhra2503** [comment]
![Wo_cust2](https://user-images.githubusercontent.com/53158022/72154958-f931d800-33d7-11ea-8249-2881193afe40.png)
